# this workflow runs bundle audit, brakeman, and rubocop
# these things probably don't need to run every commit, but probably every push

name: Code Sanitation Check

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .tool-versions
      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
  bundle-audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Bundle audit with reviewdog
        uses: tomferreira/action-bundler-audit@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  sorbet:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run sorbet with reviewdog
        uses: mihyaeru21/action-sorbet@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  brakeman:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run brakeman with reviewdog
        uses: reviewdog/action-brakeman@v2.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_install: true
          use_bundler: true
  rubocop:
    runs-on: ubuntu-latest
    needs: build
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUNDLE_ONLY: rubocop
    steps:
      - uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
